#!/bin/sh

ZONE=public
SERVICE=ssh

options="ZONE SERVICE"

run(){
	if ! firewall-cmd --permanent --zone=$ZONE --service=$SERVICE; then
		_log_err "adding service failed"
		return 1
	fi

	if ! firewall-cmd --reload; then
		_log_err "reloading firewall failed"
		return 1
	fi
}

